/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.chunlinyao.udptcprelay;

import com.github.chunlinyao.udptcprelay.client.Client;
import com.github.chunlinyao.udptcprelay.server.Server;

import java.util.LinkedHashMap;
import java.util.Map;

public class App {
    public static void main(String[] args) throws Exception {

        // now grab the first arg and see if it is a known command
        String firstArg = args.length > 0 ? args[0] : "";

        // make a list of arguments
        String[] argList = args;
        Map<String, String> argMap = new LinkedHashMap<>();
        for (String arg : argList) {
            // run twice to allow one or two dashes
            if (arg.startsWith("-")) arg = arg.substring(1);
            if (arg.startsWith("-")) arg = arg.substring(1);
            if (arg.contains("=")) {
                argMap.put(arg.substring(0, arg.indexOf("=")), arg.substring(arg.indexOf("=") + 1));
            } else {
                argMap.put(arg, "");
            }
        }

        if (firstArg.endsWith("help") || "-?".equals(firstArg)) {
            System.out.println("Usage:");
            System.out.println("    -c for client;");
            System.out.println("    -s for server;");
        }
        if (argMap.containsKey("c")) {
            startClient();
        } else if (argMap.containsKey("s")) {
            startServer();
        }
    }

    private static void startServer() throws Exception {
        new Server().start();
    }

    private static void startClient() throws Exception {
        new Client().start();
    }

}
